version: "3"
services:
  caddy:
    image: caddy:2-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - /home/ubuntu/caddy/Caddyfile:/etc/caddy/Caddyfile
      - /home/ubuntu/caddy/data:/data
      - /home/ubuntu/caddy/config:/config
  mongodb:
    image: mongo
    volumes:
      - /home/ubuntu/data:/data/db
  #your app name:
    image: #your image name
    ports:
      - 80:8080
    environment:
      APP_TOKEN: #your token that you need to add as header to request to access protected endpoints
      BOT_TOKEN: #your telegram bot token
      BOT_OWNER_TELEGRAM_ID: #your telegram account ID
      MAX_SEARCHES_PER_DAY: #max quantity of searches per user request
      MAX_SEARCHES_PER_REQUEST: #max quantity of searches per day for all users requests
      AIRPORTS_CSV_PATH: /opt/source-code/data/airports.csv
      PROXIES: #your list of proxies to avoid ban from information source separated with comma - 51.222.21.93:32768,45.1...